before_script:
    - apt-get update -qq && apt-get install -y -qq libsdl1.2-dev libpng-dev libsdl-ttf2.0-dev libsdl-image1.2-dev liblua5.1-0-dev zip

stages:
    - build

job1:
    stage: build
    script: "cd src && make && make ziprelease"
    artifacts:
        paths:
            - "*.zip"

