language: c
os:
- linux
- osx
addons:
  apt:
    packages:
    - gcc-mingw-w64-i686
    - mingw-w64-tools
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-ttf2.0-dev
    - liblua5.2-dev
sudo: false
env:
- ''
- WIN32CROSS=1
matrix:
  exclude:
  - os: osx
    env: WIN32CROSS=1
compiler:
- gcc
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update > /dev/null ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl sdl_image sdl_ttf lua ;
  fi
install:
- git fetch --unshallow
script:
- cd $TRAVIS_BUILD_DIR
- if [ "$WIN32CROSS" = "1" ] ; then make 3rdparty ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then make ; else make -j3 ; fi
- make ziprelease
before_deploy:
- git config --local user.name "Thomas Bernard"
- git config --local user.email "miniupnp@free.fr"
- git tag "$(if [ \"$WIN32CROSS\" = \"1\" ] ; then echo win32 ; else echo $TRAVIS_OS_NAME ; fi)-$(git rev-parse --abbrev-ref HEAD)-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: mSOlAr/jljyD6oGjwXcZ8pIzlwiHy/uIvcd3IaYh7Wvj0ZH189pAwFdOykNHYmpjlZqGvYQur366ooVoEGyeLtENlQzzFa1nje0xLi+UAYQtZZ4uUvYDks7/gqoPYBcQkgkiu/lNJvEtqXEa3+nu/RjK4aCDXLRN4vtg8pUamx155hNWSAHcZn/RRqn3y5yDpC/zv67tM6jxgy2b5cjlHX5+Pg1snMXU4+S/wv6R9El1QYSgSKBFAW5PyM8dwg7eTf8Jr1P99fHd9kUi3ZnDjtmMU+OQICuZXkAK4zFe8w7xsQb7tI5/caVIK4wyAwZvS1KmT3N6MZKkv/OD89HYWj4ARLj8R1VKVPb0Zz4YDfleT0OoTX8rlc0i0m8i3E2/wTGBeGaUpKuO2DFaDFzvcKcp1B51RYhaDQR7XmUaHCHMGE/nLQ9IucZn3x9Qs3foPFFUZy/q/qp8DHMJSHUyAA2D3IrJloxV/6ToMEFFrkA8LOAajkKPz9mnwWtzM0/8qUUKg7mxfwBnuXlw0qajzLteM2ECy28bdTu0PAwXQYY3M1BxZJhv57XatCpixpJtBCyTsQyHBMtbvteJLlJ8zsRSp2R4JxGNlyXV3agNOZUvj4CUGbR1rN8wQYX1W8XNoAmuWgeqAtxfBOagLuLvbyl9fARld1PIsY5mYCXdnBY=
  file_glob: true
  file:
   - "*.tgz"
   - "*.zip"
  skip_cleanup: true
  on:
    repo: miniupnp/grafx2
    branch: travis-ci
